{'src/controller.erl', [{outdir, "ebin"}]}.
{'src/main.erl', [{outdir, "ebin"}]}.
{'src/map.erl', [{outdir, "ebin"}]}.
{'src/mapquad.erl', [{outdir, "ebin"}]}.
{'src/parser.erl', [{outdir, "ebin"}]}.
{'src/pathfind.erl', [{outdir, "ebin"}]}.
{'src/quadtree.erl', [{outdir, "ebin"}]}.
{'src/socket.erl', [{outdir, "ebin"}]}.
{'src/steer.erl', [{outdir, "ebin"}]}.
{'src/visualize.erl', [{outdir, "ebin"}]}.
